const trustedHTMLPolicies = new Map()

function trustedHTMLPolicy(policyName) {
  const api = globalThis.trustedTypes
  if (!api?.createPolicy) return null

  if (!trustedHTMLPolicies.has(policyName)) {
    trustedHTMLPolicies.set(
      policyName,
      api.createPolicy(policyName, {
        // Preview HTML is generated by the package's AsciiDoc conversion pipeline.
        createHTML: (value) => String(value),
      })
    )
  }

  return trustedHTMLPolicies.get(policyName)
}

export function setTrustedHTML(element, policyName, html) {
  element.innerHTML = trustedHTMLPolicy(policyName)?.createHTML(html) ?? html
}
